application: totemic-tower-91423
version: 1
runtime: python27
instance_class: F2
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: numpy
  version: latest
- name: matplotlib
  version: latest
